"""toolkitsd.acoustmm public API."""

from .acoustic_params import AcousticParameters
from .elements import (
    AcousticElement,
    AcousticModel,
    BLIDuct,
    ComposedElement,
    ParallelElement,
    CircularLossModel,
    RectangularLossModel,
    DecascadedElement,
    neck_to_cavity_end_correction,
    neck_to_waveguide_end_correction,
    neck_to_outside_end_correction,
    total_neck_end_correction,
    ConicalDuct,
    CylindricalDuct,
    RectangularDuct,
    ElasticSlab,
    ElasticSlabSeries,
    ElasticSlabThin,
    EardrumImpedance,
    KirchhoffStinsonEquivalentFluidModel,
    KirchhoffStinsonEquivalentFluidModelRectangular,
    FlowDuct,
    EquivalentDuct,
    EquivalentSeriesImpedance,
    EquivalentParallelImpedance,
    FrozenMatrixElement,
    HRImpedanceResult,
    RectangularHRImpedanceResult,
    HelmholtzResonator,
    HelmholtzResonatorRectangular,
    HelmholtzResonatorShunt,
    InfiniteLayerModel,
    SeriesImpedanceElement,
    InfinitePlate,
    JCALayer,
    MikiLayer,
    LosslessCircularModel,
    IEC711Coupler,
    GenericFilmSeriesImpedance,
    ImpedanceJunction,
    MembraneSeriesImpedance,
    ExactFlexuralPlateSeriesImpedance,
    LowFrequencyFlexuralPlateSeriesImpedance,
    MatchedLoad,
    PlateSeriesImpedance,
    FlexuralPlateSeriesImpedance,
    RadiationImpedance,
    RigidWall,
    ViscothermalDuct,
    ViscothermalConicalDuctDiscrete,
    ViscothermalRectangularDuct,
    WaveguideElement,
)
from .mode_cutoffs import (
    first_mode_rect_duct,
    first_mode_round_duct,
    mode_frequencies_rect_duct,
    mode_frequencies_round_duct,
)
from .geometry import EarCanalBuilder
from .analytic import calculate_zp_parois_simple, integrate_3d_diffuse, tl_paroi_analytic, tl_simple_expansion_analytic

try:
    from .postprocessing import GeometryConfig, ThreeMicPostProcessor
except ModuleNotFoundError:  # Optional dependency path not bundled in this release.
    GeometryConfig = None
    ThreeMicPostProcessor = None

__all__ = [
    "AcousticParameters",
    "AcousticElement",
    "AcousticModel",
    "WaveguideElement",
    "SeriesImpedanceElement",
    "InfiniteLayerModel",
    "ComposedElement",
    "ParallelElement",
    "CircularLossModel",
    "RectangularLossModel",
    "DecascadedElement",
    "total_neck_end_correction",
    "neck_to_waveguide_end_correction",
    "neck_to_cavity_end_correction",
    "neck_to_outside_end_correction",
    "FrozenMatrixElement",
    "EquivalentDuct",
    "EquivalentSeriesImpedance",
    "EquivalentParallelImpedance",
    "HelmholtzResonatorShunt",
    "HelmholtzResonator",
    "HelmholtzResonatorRectangular",
    "HRImpedanceResult",
    "RectangularHRImpedanceResult",
    "BLIDuct",
    "CylindricalDuct",
    "RectangularDuct",
    "ConicalDuct",
    "ViscothermalConicalDuctDiscrete",
    "FlowDuct",
    "ElasticSlab",
    "ElasticSlabThin",
    "ElasticSlabSeries",
    "ViscothermalDuct",
    "ViscothermalRectangularDuct",
    "JCALayer",
    "MikiLayer",
    "ImpedanceJunction",
    "InfinitePlate",
    "PlateSeriesImpedance",
    "GenericFilmSeriesImpedance",
    "MembraneSeriesImpedance",
    "ExactFlexuralPlateSeriesImpedance",
    "LowFrequencyFlexuralPlateSeriesImpedance",
    "FlexuralPlateSeriesImpedance",
    "RigidWall",
    "MatchedLoad",
    "RadiationImpedance",
    "EardrumImpedance",
    "KirchhoffStinsonEquivalentFluidModel",
    "KirchhoffStinsonEquivalentFluidModelRectangular",
    "LosslessCircularModel",
    "IEC711Coupler",
    "mode_frequencies_rect_duct",
    "first_mode_rect_duct",
    "mode_frequencies_round_duct",
    "first_mode_round_duct",
    "EarCanalBuilder",
    "GeometryConfig",
    "ThreeMicPostProcessor",
    "tl_simple_expansion_analytic",
    "calculate_zp_parois_simple",
    "tl_paroi_analytic",
    "integrate_3d_diffuse",
]
